format="""
$status
$username$all\
$time$character"""

command_timeout = 10000

# Inserts a blank line between shell prompts
add_newline = true

[character]                            # The name of the module we are configuring is "character"
success_symbol = "[➜](bold green)"
error_symbol = "[✗](bold red)"
vicmd_symbol = "[V](bold green) "

[package]
disabled = true

[time]
disabled = false
format = '[\[🕙$time\]]($style) '
utc_time_offset = "local"

[status]
style = "bg:#FF5555 bold"
format = '[\[$symbol $common_meaning$signal_name $int\]]($style)'
map_symbol = true
disabled = false

# [git_status]
# format = '([\[$all_status$ahead_behind\]]($style) )'
# ahead = "⇡${count}"
# diverged = "⇕⇡${ahead_count}⇣${behind_count}"
# behind = "⇣${count}"
# disabled = false

[git_commit]
commit_hash_length = 4
tag_symbol = "🔖"
disabled = false

# [git_metrics]
# added_style = "bold blue"
# format = '[+$added]($added_style)/[-$deleted]($deleted_style) '
# disabled = false

[username]
style_user = "blue bold italic"
style_root = "red bold italic"
format = "[$user]($style) "
disabled = false
show_always = true
